name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what the bug is
      placeholder: When I do X, Y happens instead of Z
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: input
    id: license-url
    attributes:
      label: License URL
      description: If applicable, the mit-license.org URL affected
      placeholder: https://username.mit-license.org

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, or other relevant details
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14
